### ISSUE TITLE
Сделать первый слой (красный прямоугольник) плавающим свободно во время скролла.

### ISSUE THREAD

**Issue by panchossanchos** [martyns0n/sanchos-website#1]
Тут анимация того, что я имею ввиду — https://yadi.sk/i/hBQUtd9o3Wjt6W

**Comment by m0rtyn** [comment]
@panchossanchos 
В анимации красный слой зацикленно может прокручиваться или подразумевается, что просто в обе стороны, или и то и другое?

**Comment by panchossanchos** [comment]
И то и другое
