### ISSUE TITLE
Давай задавать красному прямоугольнику высоту и ширину равную реальной высоте окна браузера. 

### ISSUE THREAD

**Issue by panchossanchos** [martyns0n/sanchos-website#6]
(Например у меня экран 1440x900, но реальные размеры сайта в браузере 1440x803)

**Comment by m0rtyn** [comment]
@panchossanchos 
Так и должно быть. Если ты видишь обратное, то это либо особенности браузера, либо погрешности в формуле расчета. В обоих случаях я могу исправить. Хорошо если будет скрин.
